In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = pd.read_csv("Train.csv").values
x_test=pd.read_csv("Test.csv").values
print(x)


[[ 2.93416239e-01 -9.45598713e-01 -4.21105147e-01  4.06816021e-01
   5.25661832e-01 -8.21546666e+01]
 [-8.36084081e-01 -1.89228039e-01 -7.76402618e-01 -1.05383124e+00
   5.97996852e-01 -4.88979602e+01]
 [ 2.36425114e-01  1.32836018e-01 -1.47722982e-01  6.99853963e-01
  -1.87364163e-01  7.72703707e+01]
 ...
 [ 1.04417694e+00 -8.99206485e-01  1.73039905e+00 -1.87105676e+00
   4.42519647e-01 -1.07510508e+02]
 [-1.26917290e+00 -5.05215916e-03  1.85766873e+00 -1.08036482e+00
   7.36333937e-01 -4.73415578e+01]
 [-1.88400025e+00 -8.49427430e-01 -1.45227035e+00  4.88613076e-01
   1.45957580e+00 -1.15939003e+02]]


In [3]:
print(x_test)

[[ 1.01525387e+00  2.07620944e+00 -2.66434820e-01 -2.41808820e+00
  -9.80502790e-01]
 [-3.75021204e-01  9.53184528e-01  6.26719138e-01  7.04405750e-01
  -3.55489211e-01]
 [-1.02445225e+00  9.62991107e-01 -4.07942004e-01 -1.86127383e+00
   4.55201351e-01]
 ...
 [ 5.54727647e-01  1.76824345e+00 -8.97787210e-01 -1.19366107e+00
   3.40563374e-01]
 [-1.62717246e+00  8.56470994e-01 -5.65729519e-04  6.29386649e-01
   4.53382144e-01]
 [ 1.39310499e-01  5.31597186e-01 -8.53107053e-01  3.16920076e-02
   1.71489304e+00]]


In [4]:
X=x[:,:5]
Y=x[:,5]
print(X)

[[ 0.29341624 -0.94559871 -0.42110515  0.40681602  0.52566183]
 [-0.83608408 -0.18922804 -0.77640262 -1.05383124  0.59799685]
 [ 0.23642511  0.13283602 -0.14772298  0.69985396 -0.18736416]
 ...
 [ 1.04417694 -0.89920649  1.73039905 -1.87105676  0.44251965]
 [-1.2691729  -0.00505216  1.85766873 -1.08036482  0.73633394]
 [-1.88400025 -0.84942743 -1.45227035  0.48861308  1.4595758 ]]


In [5]:
print(Y)

[ -82.15466656  -48.89796018   77.2703707  ... -107.51050797  -47.34155781
 -115.93900296]


In [6]:
std=np.std(X,axis=0)
u=np.mean(X,axis=0)
print(std)
print(u)

[0.99702582 1.02145636 1.01145129 1.01687155 0.97834768]
[ 0.0041143  -0.0276038  -0.04445943 -0.04240792  0.01200535]


In [7]:
X=(X-u)/std
print(X)

[[ 0.29016495 -0.89871183 -0.37238147  0.44177059  0.52502448]
 [-0.84270473 -0.15822922 -0.72365639 -0.99464217  0.59896038]
 [ 0.23300381  0.15706968 -0.10209444  0.72994655 -0.20378187]
 ...
 [ 1.0431652  -0.8532941   1.75476416 -1.79830858  0.44004223]
 [-1.27708547  0.02207793  1.88059294 -1.0207355   0.74035908]
 [-1.89374689 -0.80456069 -1.39187219  0.52221049  1.47960738]]


In [8]:
ones=np.ones((X.shape[0],1))
print(ones)

[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]


In [9]:
X = np.hstack((ones,X))
print(X)

[[ 1.          0.29016495 -0.89871183 -0.37238147  0.44177059  0.52502448]
 [ 1.         -0.84270473 -0.15822922 -0.72365639 -0.99464217  0.59896038]
 [ 1.          0.23300381  0.15706968 -0.10209444  0.72994655 -0.20378187]
 ...
 [ 1.          1.0431652  -0.8532941   1.75476416 -1.79830858  0.44004223]
 [ 1.         -1.27708547  0.02207793  1.88059294 -1.0207355   0.74035908]
 [ 1.         -1.89374689 -0.80456069 -1.39187219  0.52221049  1.47960738]]


In [10]:
twos=np.ones((x_test.shape[0],1))
print(twos)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.

In [11]:
x_test=np.hstack((twos,x_test))
print(x_test)

[[ 1.00000000e+00  1.01525387e+00  2.07620944e+00 -2.66434820e-01
  -2.41808820e+00 -9.80502790e-01]
 [ 1.00000000e+00 -3.75021204e-01  9.53184528e-01  6.26719138e-01
   7.04405750e-01 -3.55489211e-01]
 [ 1.00000000e+00 -1.02445225e+00  9.62991107e-01 -4.07942004e-01
  -1.86127383e+00  4.55201351e-01]
 ...
 [ 1.00000000e+00  5.54727647e-01  1.76824345e+00 -8.97787210e-01
  -1.19366107e+00  3.40563374e-01]
 [ 1.00000000e+00 -1.62717246e+00  8.56470994e-01 -5.65729519e-04
   6.29386649e-01  4.53382144e-01]
 [ 1.00000000e+00  1.39310499e-01  5.31597186e-01 -8.53107053e-01
   3.16920076e-02  1.71489304e+00]]


In [12]:
df=pd.DataFrame(X)
print(df)

        0         1         2         3         4         5
0     1.0  0.290165 -0.898712 -0.372381  0.441771  0.525024
1     1.0 -0.842705 -0.158229 -0.723656 -0.994642  0.598960
2     1.0  0.233004  0.157070 -0.102094  0.729947 -0.203782
3     1.0  0.171708  0.167210 -0.530576 -0.078377 -1.333037
4     1.0 -1.702188  0.558336 -2.723087 -0.633625  1.259339
...   ...       ...       ...       ...       ...       ...
1595  1.0 -0.279908 -0.776372 -0.704645 -0.103402 -0.326218
1596  1.0 -0.080453  0.276919  0.330726  1.807941  0.335612
1597  1.0  1.043165 -0.853294  1.754764 -1.798309  0.440042
1598  1.0 -1.277085  0.022078  1.880593 -1.020736  0.740359
1599  1.0 -1.893747 -0.804561 -1.391872  0.522210  1.479607

[1600 rows x 6 columns]


In [13]:
df.head()

0         1         2         3         4         5
0  1.0  0.290165 -0.898712 -0.372381  0.441771  0.525024
1  1.0 -0.842705 -0.158229 -0.723656 -0.994642  0.598960
2  1.0  0.233004  0.157070 -0.102094  0.729947 -0.203782
3  1.0  0.171708  0.167210 -0.530576 -0.078377 -1.333037
4  1.0 -1.702188  0.558336 -2.723087 -0.633625  1.259339

In [14]:
def hypothesis(X,theta):
    return np.dot(X,theta)
def error(X,Y,theta):
    error=0.0
    m=X.shape[0]
    y_=hypothesis(X,theta)
    e=np.sum((Y-y_)**2)
    return e/m
def gradient(X,Y,theta):
    y_=hypothesis(X,theta)
    grad=np.dot(X.T,(y_ - Y))
    m=X.shape[0]
    return grad/m
def gradient_descent(X,Y,learning_rate=0.1,max_epochs=150):
    n=X.shape[1]
    print(n)
    theta=np.zeros((n,))
    print(theta)
    error_list=[]
    print(error_list)
    for i in range(max_epochs):
        
        e=error(X,Y,theta)
        error_list.append(e)
        
        grad=gradient(X,Y,theta)
        theta=theta-learning_rate*grad
    return theta,error_list


In [15]:
theta,error_list=gradient_descent(X,Y)
print(theta)

6
[0. 0. 0. 0. 0. 0.]
[]
[ 0.31883534 29.59358329 94.65065769  8.37542441 45.5230239   2.46460407]


In [16]:
print(error_list)

[12256.130414032896, 10026.033684143073, 8217.055252817618, 6749.466627013954, 5558.673187089287, 4592.334067473993, 3808.0315657917154, 3171.3849608951386, 2654.5237799458373, 2234.85183834815, 1894.04653113265, 1617.2484830009762, 1392.4052530232816, 1209.739731393694, 1061.3194764678283, 940.7077762355079, 842.6808858642628, 762.9988586786474, 698.2197865343779, 645.5492057333448, 602.71799423682, 567.8833559297998, 539.5485154072414, 516.497578530278, 497.74268728982713, 482.48114259194176, 470.06060992121985, 459.9508802381248, 451.7209479296338, 445.0204021068504, 439.5643175010901, 435.12098512481214, 431.50194759201077, 428.5539050830669, 426.15213988278555, 424.1951738531029, 422.60042706729115, 421.3006895139444, 420.24125320690837, 419.37758077512547, 418.67340992065016, 418.0992120500356, 417.6309387353912, 417.2490021205568, 416.9374455012189, 416.68326851820393, 416.47587806958705, 416.30664146076737, 416.16852270834255, 416.0557864849475, 415.96375709353555, 415.88862221

In [17]:
y_test=hypothesis(x_test,theta)
print(y_test)

[ 112.15168131  115.87973494  -25.87624513  -47.63581827 -102.51798761
  -50.28935126  -81.36834056   20.93715835  172.90061606  170.88405882
 -111.39441517  -25.59611846   -8.87206576  120.36145509   35.0939827
   41.78965456 -199.41767451   17.73984274    8.53610072  133.07315175
   61.45776797  -68.3999742  -114.50736282  -12.54694769  -64.18044493
    7.52045579   23.78466568  104.76864774   19.45714597  -31.19277989
  107.8008343   -51.11361286  215.83280577  -20.00279436 -238.03987927
  152.54776131   -8.26499061    9.13279148 -318.74458455   73.47899692
  -88.08890511 -214.922216   -248.1034524   132.6571226   -80.84247791
  101.17557399   -9.18200867   14.91511549 -104.82053117  -33.08743513
    7.17983258 -184.25131452   60.85421126 -105.23083896 -112.7061383
 -163.49561457   59.10705605  105.97835822  -79.92264279   38.71062418
   36.83619308  -56.62422748  162.70346186   38.96673302   52.65613652
   19.57221657   78.32372288   -7.31912952   -8.26016182   -3.63353609
  -27.98

In [18]:
df=pd.DataFrame(data=y_test,columns=["target"])
print(df)

         target
0    112.151681
1    115.879735
2    -25.876245
3    -47.635818
4   -102.517988
..          ...
395  -88.148472
396 -194.762380
397  123.081563
398   62.994767
399   53.281670

[400 rows x 1 columns]


In [19]:
df.to_csv("prediction.csv",index=True)